In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split# Import train_test_split function
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle#used to pick the model as we re using standard scaler and label encoder



In [34]:
#load the dataset 
data = pd.read_csv('Churn_Modelling.csv')
data.head() #display the first 5 rows of the dataset
 #get the shape of the dataset using data.shape

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [35]:
#pre process the data
#drop irrelevant frature like rownumber
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)#aixs=1 means columnwise
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [36]:
#encode cateogrical variable
label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])#fit_transform used for encoding transformation lik e convert cateogrical values into the numberical values 
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [37]:
# onehot encode the geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()
geo_encoded_value=onehot_encoder.fit_transform(data[['Geography']])
geo_encoded_value
geo_encoded_value.toarray()#convert the encoded value into array



array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [38]:
onehot_encoder.get_feature_names_out(['Geography'])#get the feature names of the onehot encoded column
geo_encoded_value = pd.DataFrame(geo_encoded_value.toarray(),columns=onehot_encoder.get_feature_names_out(['Geography']))#convert the onehot encoded value into the dataframe
geo_encoded_value

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [39]:
# combine one hot encoder colums wit originl data
data = pd.concat([data.drop("Geography",axis=1),geo_encoded_value],axis=1)#axis=1 means columnwise and drop the original geography column and add the onehot encoded column
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [40]:
## save the enocder and scaler
with open('label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder,file)#dump is used to save the label encoder in the file
with open('onehot_encoder.pkl','wb') as file:
    pickle.dump(onehot_encoder,file)#dump is used to save the onehot encoder in the file

In [41]:
# divide the dataswt into dependent feature and independent feature
X = data.drop('Exited',axis=1)#independent feature
y = data['Exited']#dependent feature
#split the data into train and test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)#random_state is used to get the same result everytime we run the code
#scale the data
scaler = StandardScaler()#scale the data means to convert the data into the same scale scale standard sclaer is used transofrm the data to have a mean of 0 and a standard deviation of 1
X_train = scaler.fit_transform(X_train)#fit_transform is used to scale the data means to normalize the data
X_test = scaler.transform(X_test)#transform is used to scale the data
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [42]:
#save the scaler
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)#dump is used to save the scaler in the file


In [75]:
#####now from here we will train ANN model(ANN IMPLEMENTATION)
X_train.shape[1]


12

In [44]:
#s-1:- making the sequential model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense#dense layer is used to add the hidden layer in the model
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard#early stopping is used to stop the training of the model when the model is not learning anything
import datetime




In [45]:
X_train.shape[1]#get the number of columns in the X_train input is 12 shape is used to get the columns of data where 1 is used to get the columns


12

In [46]:
#building model(insidethe model)
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),#input layer and  the input shape which is 12 and have 64 neurons in the hidden layer 1
    Dense(32, activation='relu'),#hidden layer 2
    Dense(1, activation='sigmoid')#output layer as we have binary classificarion so we use 1 neuron in o/p layer
])



c:\Users\aakash\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [47]:
model.summary()#get the summary of the model

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)#adam optimizer is used to optimize the model
loss=tensorflow.keras.losses.BinaryCrossentropy()#binary crossentropy is used as we have binary classification
loss


In [49]:
#COMPILE THE MODEL FOR FORWARD AND BACKWARD PROPAGATIon
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])#adam is the optimizer used to optimize the model and binary_crossentropy is the loss function used for binary classification


In [50]:
#set up the Tensorboard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")#get the current date and time



In [51]:
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)#tensorboard is used to visualize the model and get the accuracy and loss of the model
#setting up the early stopping
early_stopping = EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)#early stopping is used to stop the training of the model when the model is not learning anything



In [52]:
#train the model
model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test),callbacks=[early_stopping,tensorflow_callback])#train the model with 100 epochs and validation data is used to validate the model and early stopping is used to stop the training of the model when the model is not learning anything
#epochs is used to train the model for 100 times
#callbacks is used to stop the training of the model when the model is not learning anything


Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7978 - loss: 0.4553 - val_accuracy: 0.8530 - val_loss: 0.3542
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8512 - loss: 0.3724 - val_accuracy: 0.8545 - val_loss: 0.3489
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8527 - loss: 0.3487 - val_accuracy: 0.8600 - val_loss: 0.3390
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8638 - loss: 0.3311 - val_accuracy: 0.8550 - val_loss: 0.3407
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8518 - loss: 0.3476 - val_accuracy: 0.8610 - val_loss: 0.3382
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8668 - loss: 0.3364 - val_accuracy: 0.8600 - val_loss: 0.3399
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3296 - val_accuracy: 0.8570 - val_loss: 0.3416
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8605 - loss: 0.3291 - val_accu

In [53]:
model.save('model.h5')#save the model in the file


In [54]:
#load the tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [55]:
%tensorboard --logdir logs/fit#load the tensorboard to visualize the model


Reusing TensorBoard on port 6006 (pid 17636), started 2:41:37 ago. (Use '!kill 17636' to kill it.)

In [56]:
#load the traiend model,scaler pickle and onehot encoder
#load the model
model = tf.keras.models.load_model('model.h5')#load the model
#load encoders and scalers
with open('label_encoder.pkl','rb') as file:
    label_encoder=pickle.load(file)#load the label encoder  
with open('onehot_encoder.pkl','rb') as file:
    onehot_encoder=pickle.load(file)#load the onehot encoder
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)#load the scaler


In [57]:
#example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender':'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [68]:
#one hot encode the geography 
geo = onehot_encoder.transform([[input_data['Geography']]]).toarray().reshape(1,-1)
geo_encoded_dataframe = pd.DataFrame(geo,columns=onehot_encoder.get_feature_names_out(['Geography']))
geo_encoded_dataframe




c:\Users\aakash\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [67]:
#cverting input data to dataframe so that we can combine onehot encoded column with the input data
input_df=pd.DataFrame([input_data])
input_df


CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [69]:
#encode the cateogrical variables 
input_df['Gender'] = label_encoder.transform(input_df['Gender'])
input_df = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_dataframe],axis=1)#CONCATENATE THE ONEHOT ENCODED COLUMN WITH THE INPUT DATA
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [70]:
#scaling the input data 
input_data_scaled = scaler.transform(input_df)
input_data_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [71]:
##predict the churn
prediction = model.predict(input_data_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0.02920124]], dtype=float32)

In [72]:
prediction_probability = prediction[0][0]
prediction_probability

0.029201243

In [73]:
if prediction_probability>0.5:
    print('Customer is likely to churn')
else:
    print('Customer is not likely to churn')
    

Customer is not likely to churn
